### ISSUE TITLE
[SUPPORT] How to Check Test files by Mypy CI

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/hist#15]
## Describe your questions

I have used mypy according to https://scikit-hep.org/developer/style#type-checking-new. My pre-commit profig file is like this:

```yaml
repos:
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: check-added-large-files
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-case-conflict
  - id: check-symlinks
  - id: check-yaml
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.770
  hooks:
  - id: mypy
    files: all  # I tried tests and src, but none worked
```

I deliberately put a type error in a test file, but pre-commit did not find it. How to make mypy CI work for unit tests?
